### ISSUE TITLE
Can't initialize app due to file permissions

### ISSUE THREAD

**Issue by johrstrom** [OSC/frame-renderer#15]
In version 0.1.0_rc1 I got this error while initializing the application in our development environment.

```bash
Per user setup failed for script at /var/www/ood/apps/sys/frame-renderer/./bin/setup-production for user johrstrom with output: /opt/rh/rh-ruby24/root/usr/share/ruby/fileutils.rb:230:in `mkdir': Permission denied @ dir_s_mkdir - /run/user/0/spring-30961 (Errno::EACCES)
	from /opt/rh/rh-ruby24/root/usr/share/ruby/fileutils.rb:230:in `fu_mkdir'
	from /opt/rh/rh-ruby24/root/usr/share/ruby/fileutils.rb:208:in `block (2 levels) in mkdir_p'
	from /opt/rh/rh-ruby24/root/usr/share/ruby/fileutils.rb:206:in `reverse_each'
	from /opt/rh/rh-ruby24/root/usr/share/ruby/fileutils.rb:206:in `block in mkdir_p'
	from /opt/rh/rh-ruby24/root/usr/share/ruby/fileutils.rb:191:in `each'
	from /opt/rh/rh-ruby24/root/usr/share/ruby/fileutils.rb:191:in `mkdir_p'
	from /var/www/ood/apps/sys/frame-renderer/vendor/bundle/ruby/2.4.0/gems/spring-2.1.0/lib/spring/env.rb:40:in `tmp_path'
```

Apparently `XDG_RUNTIME_DIR` in our dev environment is set to `/run/user/0`? Because it did figure out my UID to be 30961.

```ruby
    def tmp_path
      path = Pathname.new(
        ENV["SPRING_TMP_PATH"] ||
          File.join(ENV['XDG_RUNTIME_DIR'] || Dir.tmpdir, "spring-#{Process.uid}")
      )
      FileUtils.mkdir_p(path) unless path.exist?
      path
    end
```

**Comment by johrstrom** [comment]
I'm just going to force  `ENV["SPRING_TMP_PATH"]`  to be `Dir.tmpdir`.

**Comment by ericfranz** [comment]
`spring` should be removed:

https://github.com/rails/spring#removal
